title   Arch Linux (cachyos custom)
linux   /vmlinuz-linux-cachyos
initrd  /initramfs-linux-cachyos.img
options root=PARTUUID=0d1352ad-4e1b-4618-a111-e0372428181e zswap.enabled=0 rw rootfstype=ext4 i8042.reset i8042.nomux i8042.noloop intel_pstate=passive i915.enable_psr=1 nmi_watchdog=0 intel_ish=1 intel_rapl=1 acpi_osi="Windows 2020"
